// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CheckUpdate(arg1:string):Promise<main.AppUpdateInfo>;

export function ClearSession():Promise<void>;

export function DeviceLogin(arg1:string):Promise<main.LoginResult>;

export function GetEmployeeName():Promise<string>;

export function GetFollowStaffList():Promise<Array<main.FollowStaffItem>>;

export function GetMacAddress():Promise<string>;

export function GetMachineID():Promise<string>;

export function GetPlatform():Promise<string>;

export function GetServerURL():Promise<string>;

export function IsLoggedIn():Promise<boolean>;

export function ParseOrderText(arg1:string):Promise<main.ParseTextResult>;

export function SelectAttachmentFile():Promise<string>;

export function SelectScreenshotFile():Promise<string>;

export function SetAlwaysOnTop(arg1:boolean):Promise<void>;

export function SetServerURL(arg1:string):Promise<void>;

export function SubmitOrder(arg1:string,arg2:string,arg3:string,arg4:number,arg5:Array<string>,arg6:string,arg7:string,arg8:string,arg9:number,arg10:string,arg11:string):Promise<main.SubmitResult>;

export function UploadAttachmentBase64(arg1:string):Promise<main.UploadAttachmentResult>;

export function UploadAttachmentFile(arg1:string):Promise<main.UploadAttachmentResult>;

export function UploadScreenshot(arg1:string):Promise<main.OCRResult>;

export function UploadScreenshotBase64(arg1:string):Promise<main.OCRResult>;
