// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ClearSession():Promise<void>;

export function DeviceLogin(arg1:string):Promise<main.LoginResult>;

export function GetEmployeeName():Promise<string>;

export function GetMacAddress():Promise<string>;

export function GetPlatform():Promise<string>;

export function GetServerURL():Promise<string>;

export function IsLoggedIn():Promise<boolean>;

export function SelectScreenshotFile():Promise<string>;

export function SetServerURL(arg1:string):Promise<void>;

export function SubmitOrder(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:number,arg7:number):Promise<main.SubmitResult>;

export function UploadScreenshot(arg1:string):Promise<main.OCRResult>;
