// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckUpdate(arg1) {
  return window['go']['main']['App']['CheckUpdate'](arg1);
}

export function ClearSession() {
  return window['go']['main']['App']['ClearSession']();
}

export function DeviceLogin(arg1) {
  return window['go']['main']['App']['DeviceLogin'](arg1);
}

export function GetEmployeeName() {
  return window['go']['main']['App']['GetEmployeeName']();
}

export function GetMacAddress() {
  return window['go']['main']['App']['GetMacAddress']();
}

export function GetMachineID() {
  return window['go']['main']['App']['GetMachineID']();
}

export function GetPlatform() {
  return window['go']['main']['App']['GetPlatform']();
}

export function GetServerURL() {
  return window['go']['main']['App']['GetServerURL']();
}

export function IsLoggedIn() {
  return window['go']['main']['App']['IsLoggedIn']();
}

export function SelectAttachmentFile() {
  return window['go']['main']['App']['SelectAttachmentFile']();
}

export function SelectScreenshotFile() {
  return window['go']['main']['App']['SelectScreenshotFile']();
}

export function SetServerURL(arg1) {
  return window['go']['main']['App']['SetServerURL'](arg1);
}

export function SubmitOrder(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8) {
  return window['go']['main']['App']['SubmitOrder'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
}

export function UploadAttachmentBase64(arg1) {
  return window['go']['main']['App']['UploadAttachmentBase64'](arg1);
}

export function UploadAttachmentFile(arg1) {
  return window['go']['main']['App']['UploadAttachmentFile'](arg1);
}

export function UploadScreenshot(arg1) {
  return window['go']['main']['App']['UploadScreenshot'](arg1);
}

export function UploadScreenshotBase64(arg1) {
  return window['go']['main']['App']['UploadScreenshotBase64'](arg1);
}
